development:
  adapter: sqlite3
  database: db/crm.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test_sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/prod_sqlite3.db
  pool: 5
  timeout: 5000